// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCAI.Infrastructure;

#nullable disable

namespace SCAI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220054930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SCAI.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimalRoleLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rifle blaster padrão para Stormtroopers",
                            MinimalRoleLevel = 3,
                            Name = "Rifle blaster E-11",
                            Quantity = 500
                        },
                        new
                        {
                            Id = 2,
                            Description = "Capacete branco padrão com comlink integrado",
                            MinimalRoleLevel = 3,
                            Name = "Capacete de stormtrooper",
                            Quantity = 300
                        },
                        new
                        {
                            Id = 3,
                            Description = "Armadura composta de plastoide branco",
                            MinimalRoleLevel = 3,
                            Name = "Armadura de stormtrooper",
                            Quantity = 300
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dispositivo explosivo térmico Classe-A",
                            MinimalRoleLevel = 3,
                            Name = "Detonador térmico",
                            Quantity = 150
                        },
                        new
                        {
                            Id = 5,
                            Description = "Pistola blaster compacta para combate a curta distância",
                            MinimalRoleLevel = 3,
                            Name = "Blaster de repetição leve SE-14r",
                            Quantity = 200
                        },
                        new
                        {
                            Id = 6,
                            Description = "Equipamento utilitário para escalar superfícies",
                            MinimalRoleLevel = 3,
                            Name = "Gancho de escalada",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dispositivo de visão aprimorada com telêmetro",
                            MinimalRoleLevel = 3,
                            Name = "Eletrobinóculos",
                            Quantity = 80
                        },
                        new
                        {
                            Id = 22,
                            Description = "Granada de impacto não-letais para dispersão",
                            MinimalRoleLevel = 3,
                            Name = "Granada de concussão",
                            Quantity = 120
                        },
                        new
                        {
                            Id = 23,
                            Description = "Comunicador de curto alcance para patrulhas",
                            MinimalRoleLevel = 3,
                            Name = "Comlink de campo",
                            Quantity = 250
                        },
                        new
                        {
                            Id = 24,
                            Description = "Ferramentas e solventes para limpeza e ajuste",
                            MinimalRoleLevel = 3,
                            Name = "Kit de manutenção de blaster",
                            Quantity = 180
                        },
                        new
                        {
                            Id = 25,
                            Description = "Célula de energia sobressalente para armas e equipamentos",
                            MinimalRoleLevel = 3,
                            Name = "Pack de energia reserva",
                            Quantity = 400
                        },
                        new
                        {
                            Id = 26,
                            Description = "Arma de contenção com descarga elétrica",
                            MinimalRoleLevel = 3,
                            Name = "Bastão de choque",
                            Quantity = 90
                        },
                        new
                        {
                            Id = 27,
                            Description = "Suprimentos compactos para missões prolongadas",
                            MinimalRoleLevel = 3,
                            Name = "Ração de campo Imperial",
                            Quantity = 600
                        },
                        new
                        {
                            Id = 28,
                            Description = "Filtro substituível para ambientes com fumaça e poeira",
                            MinimalRoleLevel = 3,
                            Name = "Filtro de respiração",
                            Quantity = 220
                        },
                        new
                        {
                            Id = 29,
                            Description = "Iluminação portátil com modos estroboscópicos",
                            MinimalRoleLevel = 3,
                            Name = "Lanterna tática",
                            Quantity = 160
                        },
                        new
                        {
                            Id = 30,
                            Description = "Detector portátil de proximidade e deslocamento",
                            MinimalRoleLevel = 3,
                            Name = "Sensor de movimento",
                            Quantity = 70
                        },
                        new
                        {
                            Id = 31,
                            Description = "Dispositivo de restrição com travas magnetizadas",
                            MinimalRoleLevel = 3,
                            Name = "Algemas magnéticas",
                            Quantity = 140
                        },
                        new
                        {
                            Id = 32,
                            Description = "Kit de primeiros socorros com selantes e estimulantes",
                            MinimalRoleLevel = 3,
                            Name = "Medkit de campo",
                            Quantity = 110
                        },
                        new
                        {
                            Id = 33,
                            Description = "Conjunto de placas para reparo rápido de danos",
                            MinimalRoleLevel = 3,
                            Name = "Placas de reposição de armadura",
                            Quantity = 75
                        },
                        new
                        {
                            Id = 34,
                            Description = "Cargas de baixa potência para exercícios",
                            MinimalRoleLevel = 3,
                            Name = "Munição de treinamento",
                            Quantity = 1000
                        },
                        new
                        {
                            Id = 8,
                            Description = "Blaster pesado para suporte de fogo sustentado",
                            MinimalRoleLevel = 2,
                            Name = "Rifle blaster pesado DLT-19",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ombreira de insígnia de patente para comandantes",
                            MinimalRoleLevel = 2,
                            Name = "Ombreira de comando de oficial",
                            Quantity = 25
                        },
                        new
                        {
                            Id = 10,
                            Description = "Dispositivo de autorização de segurança para áreas restritas",
                            MinimalRoleLevel = 2,
                            Name = "Cilindro de código Imperial",
                            Quantity = 30
                        },
                        new
                        {
                            Id = 11,
                            Description = "Dispositivo de comunicação holográfica portátil",
                            MinimalRoleLevel = 2,
                            Name = "Holoprojetor",
                            Quantity = 20
                        },
                        new
                        {
                            Id = 12,
                            Description = "Blaster de repetição poderoso para assalto pesado",
                            MinimalRoleLevel = 2,
                            Name = "Blaster de repetição leve T-21",
                            Quantity = 40
                        },
                        new
                        {
                            Id = 13,
                            Description = "Dispositivo de armazenamento de dados criptografados e comunicação",
                            MinimalRoleLevel = 2,
                            Name = "Datapad Imperial",
                            Quantity = 35
                        },
                        new
                        {
                            Id = 14,
                            Description = "Moto speeder 74-Z para reconhecimento",
                            MinimalRoleLevel = 2,
                            Name = "Moto speeder de scout trooper",
                            Quantity = 15
                        },
                        new
                        {
                            Id = 35,
                            Description = "Óptica avançada com telemetria e marcação de alvos",
                            MinimalRoleLevel = 2,
                            Name = "Binóculos de comando",
                            Quantity = 18
                        },
                        new
                        {
                            Id = 36,
                            Description = "Uniforme de serviço para operações e inspeções",
                            MinimalRoleLevel = 2,
                            Name = "Uniforme de oficial Imperial",
                            Quantity = 22
                        },
                        new
                        {
                            Id = 37,
                            Description = "Cartografia tática com rotas e pontos de interesse",
                            MinimalRoleLevel = 2,
                            Name = "Mapa estelar atualizado",
                            Quantity = 12
                        },
                        new
                        {
                            Id = 38,
                            Description = "Módulos para cifrar transmissões em campo",
                            MinimalRoleLevel = 2,
                            Name = "Kit de criptografia de comunicações",
                            Quantity = 14
                        },
                        new
                        {
                            Id = 39,
                            Description = "Unidade aérea compacta para varredura e vigilância",
                            MinimalRoleLevel = 2,
                            Name = "Drone de reconhecimento",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 40,
                            Description = "Acessório de mira para tiros de precisão a longa distância",
                            MinimalRoleLevel = 2,
                            Name = "Mira macrobinocular",
                            Quantity = 16
                        },
                        new
                        {
                            Id = 41,
                            Description = "Credencial para áreas de segurança intermediária",
                            MinimalRoleLevel = 2,
                            Name = "Cartão de acesso nível-2",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 42,
                            Description = "Terminal compacto para coordenação de unidades",
                            MinimalRoleLevel = 2,
                            Name = "Console portátil de estratégia",
                            Quantity = 9
                        },
                        new
                        {
                            Id = 43,
                            Description = "Transponder para acompanhamento de ativos e patrulhas",
                            MinimalRoleLevel = 2,
                            Name = "Módulo de rastreamento",
                            Quantity = 20
                        },
                        new
                        {
                            Id = 44,
                            Description = "Arma lateral padronizada para oficiais",
                            MinimalRoleLevel = 2,
                            Name = "Pistola blaster RK-3",
                            Quantity = 60
                        },
                        new
                        {
                            Id = 45,
                            Description = "Insígnia oficial para validação de ordens",
                            MinimalRoleLevel = 2,
                            Name = "Selo de autorização Imperial",
                            Quantity = 30
                        },
                        new
                        {
                            Id = 46,
                            Description = "Armazenamento endurecido para documentos sigilosos",
                            MinimalRoleLevel = 2,
                            Name = "Cofre de dados portátil",
                            Quantity = 11
                        },
                        new
                        {
                            Id = 47,
                            Description = "Ferramentas de contenção e coleta de informações",
                            MinimalRoleLevel = 2,
                            Name = "Kit de interrogatório",
                            Quantity = 6
                        },
                        new
                        {
                            Id = 15,
                            Description = "Cristal kyber sintético para sabres de luz Sith",
                            MinimalRoleLevel = 1,
                            Name = "Cristal kyber (vermelho)",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 16,
                            Description = "Arma elegante para uma era mais...incivilizada",
                            MinimalRoleLevel = 1,
                            Name = "Sabre de luz Sith",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 17,
                            Description = "Repositório antigo de conhecimento do lado sombrio",
                            MinimalRoleLevel = 1,
                            Name = "Holocron Sith",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "Câmara médica hiperbárica para o Lorde das Trevas",
                            MinimalRoleLevel = 1,
                            Name = "Câmara de meditação do Darth Vader",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 19,
                            Description = "Amplificadores para canalizar energia do lado sombrio",
                            MinimalRoleLevel = 1,
                            Name = "Manoplas de relâmpago da Força",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 20,
                            Description = "Armadura carmesim dos guardas de elite do Imperador",
                            MinimalRoleLevel = 1,
                            Name = "Armadura da guarda real do Imperador",
                            Quantity = 8
                        },
                        new
                        {
                            Id = 21,
                            Description = "Capa preta tradicional usada por Lordes Sith",
                            MinimalRoleLevel = 1,
                            Name = "Capa do lorde Sith",
                            Quantity = 4
                        },
                        new
                        {
                            Id = 48,
                            Description = "Máscara ritual com filtros para ambientes hostis",
                            MinimalRoleLevel = 1,
                            Name = "Máscara de respiração Sith",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 49,
                            Description = "Anel com sigilo antigo usado em cerimônias",
                            MinimalRoleLevel = 1,
                            Name = "Anel sigiloso Sith",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 50,
                            Description = "Compêndio de rituais e fórmulas do lado sombrio",
                            MinimalRoleLevel = 1,
                            Name = "Tomo de alquimia Sith",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 51,
                            Description = "Suporte de recuperação com parâmetros ajustados",
                            MinimalRoleLevel = 1,
                            Name = "Cápsula de bacta personalizada",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 52,
                            Description = "Cristal raro para experimentos de canalização",
                            MinimalRoleLevel = 1,
                            Name = "Cristal kyber (negro)",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 53,
                            Description = "Dispositivo para amplificar efeitos de tortura",
                            MinimalRoleLevel = 1,
                            Name = "Emissor de campo de dor",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 54,
                            Description = "Relíquia com gravuras protetoras e maldições",
                            MinimalRoleLevel = 1,
                            Name = "Amuleto de proteção sombria",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 55,
                            Description = "Arma vibro com foco ritual para combate",
                            MinimalRoleLevel = 1,
                            Name = "Lâmina vibro encantada",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 56,
                            Description = "Artefato resgatado de santuários ocultos",
                            MinimalRoleLevel = 1,
                            Name = "Relíquia de Exegol",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 57,
                            Description = "Unidade de observação adaptada a ordens Sith",
                            MinimalRoleLevel = 1,
                            Name = "Droid sonda corrompido",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 58,
                            Description = "Objeto de concentração para rituais e treinamento",
                            MinimalRoleLevel = 1,
                            Name = "Foco de meditação sombria",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 59,
                            Description = "Vestuário cerimonial para conclaves do lado sombrio",
                            MinimalRoleLevel = 1,
                            Name = "Capa cerimonial Sith",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 60,
                            Description = "Dispositivo de abertura e proteção de holocrons",
                            MinimalRoleLevel = 1,
                            Name = "Chave holocrônica",
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("SCAI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
